name: Manually Deploy to Heroku

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
          docker_heroku_process_type: web
          stack: "container"
          region: "us"
        env:
          HD_BOT_TOKEN: ${{secrets.BOT_TOKEN}}
          HD_OWNER_ID: "1892794121"
          HD_TELEGRAM_API: "13194525"
          HD_TELEGRAM_HASH: "885808ded765c1a80bcac70aa2688a8a"
          HD_DATABASE_URL: "mongodb+srv://bots:2007@cluster0.gkuudck.mongodb.net/?retryWrites=true&w=majority"
          HD_UPSTREAM_REPO: "https://gitlab.com/mysterysd.sd/WZML-X"
          HD_UPSTREAM_BRANCH: "hk_wzmlx"
          HD_TORRENT_TIMEOUT: "0"
